//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOlimpiada.DatosRepositorio.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complejo
    {
        public decimal ComplejoId { get; set; }
        public decimal SedeOlimpicaId { get; set; }
        public string Localizacion { get; set; }
        public string JefeDeOrganizacion { get; set; }
        public Nullable<decimal> AreaTotal { get; set; }
        public Nullable<decimal> PresupuestoAproximando { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
    }
}
