//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOlimpiada.DatosRepositorio.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlimpiadaDBEntities : DbContext
    {
        public OlimpiadaDBEntities()
            : base("name=OlimpiadaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evento_Comisario> Evento_Comisario { get; set; }
        public virtual DbSet<Evento_Equipamento> Evento_Equipamento { get; set; }
        public virtual DbSet<SedeOlimpica> SedeOlimpica { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Complejo> Complejo { get; set; }
        public virtual DbSet<Comisario> Comisario { get; set; }
        public virtual DbSet<Deporte> Deporte { get; set; }
        public virtual DbSet<Equipamento> Equipamento { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoEquipamento_View> EventoEquipamento_View { get; set; }
        public virtual DbSet<EventoComisario_View> EventoComisario_View { get; set; }
    }
}
