//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOlimpiada.DatosRepositorio.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Comisario
    {
        public decimal EventoId { get; set; }
        public decimal ComisarioId { get; set; }
    }
}
