//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOlimpiada.DatosRepositorio.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoEquipamento_View
    {
        public Nullable<decimal> EquipamentoId { get; set; }
        public decimal EventoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
